apiVersion: v1
kind: Pod
metadata:
  name: model-downloader
  namespace: ml

spec:
  restartPolicy: Never

  containers:
  - name: downloader
    image: alpine:3.20

    command:
    - sh
    - -c
    - |
      apk add --no-cache curl tar
      mkdir -p /models
      cd /models

      curl -L \
        https://github.com/REY1405/mlops/releases/download/v1/tiny-gpt2.tar.gz \
        -o tiny-gpt2.tar.gz

      tar -xzf tiny-gpt2.tar.gz

      echo "Model downloaded"
      ls -lah /models

      sleep 3600

    volumeMounts:
    - name: model-storage
      mountPath: /models

  volumes:
  - name: model-storage
    persistentVolumeClaim:
      claimName: tiny-gpt2-pvc