apiVersion: v1
kind: Pod
metadata:
  name: model-loader
  namespace: ml
spec:
  containers:
    - name: loader
      image: busybox
      command:
        - sh
        - -c
        - sleep 36000

      volumeMounts:
        - name: model-storage
          mountPath: /models

  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: tinyllama-pvc